import { unzipSync } from "fflate";
import {
  blankRule,
  issues,
  type Project,
  type Rule,
  type XccdfStatus,
} from "./generate.ts";
const O = "http://oval.mitre.org/XMLSchema/oval-definitions-5";
const I = O + "#independent";
const L = O + "#linux";
const U = O + "#unix";
const C = "http://oval.mitre.org/XMLSchema/oval-common-5";
const X = "http://checklists.nist.gov/xccdf/1.2";
const D = "http://purl.org/dc/elements/1.1/";
const MAX = 10 * 1024 * 1024;
function fail(message: string): never {
  throw new Error(message);
}
const kids = (el: Element) =>
  Array.from(el.childNodes).filter((n): n is Element => n.nodeType === 1);
function children(el: Element, name: string, ns = el.namespaceURI) {
  return kids(el).filter((n) => n.localName === name && n.namespaceURI === ns);
}
function one(el: Element, name: string, ns = el.namespaceURI): Element {
  const found = children(el, name, ns);
  if (found.length !== 1)
    fail(`Expected one ${name} element in ${el.localName}.`);
  return found[0];
}
function text(el: Element, name: string) {
  const node = one(el, name);
  leaf(node);
  return node.textContent || "";
}
function shape(el: Element, allowed: string[], attrs: string[] = []) {
  for (const child of kids(el))
    if (!allowed.includes(child.localName || ""))
      fail(
        `Unsupported ${child.localName} in ${el.localName}. This ZIP cannot be edited without losing content.`,
      );
  for (const attr of Array.from(el.attributes))
    if (
      attr.namespaceURI !== "http://www.w3.org/2000/xmlns/" &&
      !(
        attr.namespaceURI === "http://www.w3.org/XML/1998/namespace" &&
        attr.localName === "lang"
      ) &&
      !attrs.includes(attr.name)
    )
      fail(`Unsupported ${attr.name} attribute on ${el.localName}.`);
}
function value(el: Element, name: string, expected: string, optional = false) {
  const actual = el.getAttribute(name);
  if (optional && actual === null) return;
  if (actual !== expected)
    fail(`Unsupported ${el.localName} ${name}: expected ${expected}.`);
}
function leaf(el: Element, attrs: string[] = []) {
  shape(el, [], attrs);
}
function boolean(el: Element, name: string): boolean {
  const v = el.getAttribute(name);
  if (v === "true" || v === "1") return true;
  if (v === "false" || v === "0") return false;
  return fail(`Missing or invalid ${name} on ${el.localName}.`);
}
function index(nodes: Element[]) {
  const map = new Map<string, Element>();
  for (const node of nodes) {
    const id = node.getAttribute("id");
    if (!id || map.has(id)) fail("Missing or duplicate XML identifier.");
    map.set(id, node);
  }
  return map;
}
function parse(bytes: Uint8Array, name: string) {
  let raw: string;
  try {
    raw = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch {
    return fail(`${name}: XML must be UTF-8.`);
  }
  if (/<!DOCTYPE|<!ENTITY/i.test(raw))
    fail(`${name}: DTDs and entity declarations are not allowed.`);
  const doc = new DOMParser().parseFromString(raw, "application/xml");
  if (!doc.documentElement || doc.getElementsByTagName("parsererror").length)
    fail(`${name}: malformed XML.`);
  return doc.documentElement;
}
const unescapeRegexLiteral = (value: string) =>
  value.replace(/\\([.*+?^${}()|[\]\\])/g, "$1");

/** Imports the exact Linux OVAL subset generated by this editor. */
export function importProfileZip(bytes: Uint8Array): Project {
  if (bytes.length > MAX) fail("ZIP must be smaller than 10 MB.");
  let count = 0,
    total = 0;
  const names = new Set<string>();
  let files: Record<string, Uint8Array>;
  try {
    files = unzipSync(bytes, {
      filter(file) {
        if (++count > 20) fail("ZIP contains too many entries.");
        if (
          file.name.includes("\\") ||
          file.name.startsWith("/") ||
          file.name.split("/").some((p) => p === ".." || p === ".") ||
          names.has(file.name)
        )
          fail("ZIP contains duplicate or unsafe paths.");
        names.add(file.name);
        if (file.name.endsWith("/")) return false;
        if (!file.name.toLowerCase().endsWith(".xml"))
          fail("ZIP must contain only OVAL XML and XCCDF XML.");
        total += file.originalSize;
        if (file.originalSize > MAX || total > 2 * MAX)
          fail("Uncompressed XML exceeds the 20 MB limit.");
        if (file.compression !== 0 && file.compression !== 8)
          fail("Unsupported ZIP compression.");
        return true;
      },
    });
  } catch (e) {
    return fail("Cannot import ZIP: " + (e as Error).message);
  }
  const entries = Object.entries(files);
  if (entries.length !== 2)
    fail("ZIP must contain exactly two files: OVAL XML and XCCDF XML.");
  let oval: Element | undefined,
    benchmark: Element | undefined,
    ovalName = "",
    xccdfName = "";
  for (const [name, data] of entries) {
    if (data.length > MAX) fail("XML file exceeds the 10 MB limit.");
    const root = parse(data, name);
    if (root.localName === "oval_definitions" && root.namespaceURI === O) {
      if (oval)
        fail("ZIP contains two OVAL files; an XCCDF benchmark is required.");
      oval = root;
      ovalName = name;
    } else if (root.localName === "Benchmark" && root.namespaceURI === X) {
      if (benchmark)
        fail("ZIP contains two XCCDF files; OVAL definitions are required.");
      benchmark = root;
      xccdfName = name;
    } else
      fail(
        `${name}: expected an OVAL definitions document or an XCCDF Benchmark document.`,
      );
  }
  if (!oval || !benchmark)
    fail("Both OVAL definitions and an XCCDF benchmark are required.");
  // Reject foreign namespace elements and unsupported structures rather than discarding them.
  for (const root of [oval, benchmark])
    index(
      [root, ...Array.from(root.getElementsByTagName("*"))].filter((el) =>
        el.hasAttribute("id"),
      ),
    );
  for (const root of [oval, benchmark])
    for (const node of [root, ...Array.from(root.getElementsByTagName("*"))]) {
      const allowed = root === oval ? [O, I, L, U, C] : [X, D];
      if (!allowed.includes(node.namespaceURI || ""))
        fail(`Unexpected XML namespace on ${node.localName}.`);
    }
  shape(oval, ["generator", "definitions", "tests", "objects", "states"]);
  const generator = one(oval, "generator");
  shape(generator, [
    "product_name",
    "product_version",
    "schema_version",
    "timestamp",
  ]);
  if (one(generator, "schema_version", C).textContent !== "5.11")
    fail("This OVAL schema version is not supported by the editor.");
  const defsNode = one(oval, "definitions"),
    testsNode = one(oval, "tests"),
    objectsNode = one(oval, "objects");
  shape(defsNode, ["definition"]);
  shape(testsNode, [
    "textfilecontent54_test",
    "systemdunitproperty_test",
    "dpkginfo_test",
    "rpminfo_test",
    "file_test",
  ]);
  shape(objectsNode, [
    "textfilecontent54_object",
    "systemdunitproperty_object",
    "dpkginfo_object",
    "rpminfo_object",
    "file_object",
  ]);
  const defs = index(children(defsNode, "definition"));
  const tests = index(kids(testsNode));
  const objects = index(kids(objectsNode));
  const stateContainers = children(oval, "states");
  if (stateContainers.length > 1)
    fail("OVAL contains multiple states sections.");
  const statesNode = stateContainers[0];
  if (statesNode)
    shape(statesNode, ["systemdunitproperty_state", "file_state"]);
  const states = index(statesNode ? kids(statesNode) : []);
  if (!defs.size || defs.size > 1000)
    fail("ZIP must have between 1 and 1,000 definitions.");
  shape(
    benchmark,
    [
      "status",
      "title",
      "description",
      "version",
      "metadata",
      "Profile",
      "Rule",
    ],
    ["id"],
  );
  for (const metadata of children(benchmark, "metadata")) {
    shape(metadata, ["publisher"]);
    const publisher = one(metadata, "publisher", D);
    leaf(publisher);
  }
  const status = one(benchmark, "status");
  leaf(status, ["date"]);
  const statusValue = status.textContent || "";
  if (
    !["incomplete", "draft", "interim", "accepted", "deprecated"].includes(
      statusValue,
    )
  )
    fail("Unsupported XCCDF benchmark status.");
  const profile = one(benchmark, "Profile");
  shape(profile, ["title", "select"], ["id"]);
  const profileTitle = text(profile, "title");
  const ruleNodes = children(benchmark, "Rule");
  const ruleMap = index(ruleNodes);
  const selected = new Map<string, boolean>();
  for (const select of children(profile, "select")) {
    leaf(select, ["idref", "selected"]);
    const id = select.getAttribute("idref") || "";
    if (!ruleMap.has(id) || selected.has(id))
      fail("Profile selections contain a missing or duplicate rule reference.");
    selected.set(id, boolean(select, "selected"));
  }
  if (ruleNodes.length !== defs.size || selected.size !== ruleNodes.length)
    fail(
      "Import requires one profile selection and one XCCDF rule per OVAL definition.",
    );
  let namespace = "";
  const seenDefs = new Set<string>(),
    seenTests = new Set<string>(),
    seenObjects = new Set<string>(),
    seenStates = new Set<string>();
  const rules: Rule[] = ruleNodes.map((rule) => {
    shape(
      rule,
      ["title", "description", "check"],
      ["id", "selected", "severity"],
    );
    boolean(rule, "selected");
    const check = one(rule, "check");
    shape(check, ["check-content-ref"], ["system"]);
    value(check, "system", O);
    const ref = one(check, "check-content-ref");
    leaf(ref, ["href", "name"]);
    const href = ref.getAttribute("href") || "";
    const folder = xccdfName.slice(0, xccdfName.lastIndexOf("/") + 1);
    if (href !== ovalName.slice(folder.length) || !ovalName.startsWith(folder))
      fail(
        "XCCDF must reference its companion OVAL file in the same archive folder.",
      );
    const defId = ref.getAttribute("name") || "";
    const def = defs.get(defId);
    if (!def || seenDefs.has(defId))
      fail("XCCDF has a missing or duplicate OVAL definition reference.");
    seenDefs.add(defId);
    const match =
      /^oval:([a-zA-Z0-9]+(?:[.\-][a-zA-Z0-9]+)*):def:([1-9][0-9]*)$/.exec(
        defId,
      );
    if (!match) fail("Unsupported OVAL definition ID.");
    if (namespace && namespace !== match[1])
      fail("Definitions must share one namespace.");
    namespace = match[1];
    const id = Number(match[2]);
    if (!Number.isSafeInteger(id)) fail("OVAL definition ID is too large.");
    shape(def, ["metadata", "criteria"], ["id", "version", "class"]);
    value(def, "class", "compliance");
    value(def, "version", "1");
    const metadata = one(def, "metadata");
    shape(metadata, ["title", "description"]);
    const title = text(rule, "title"),
      description = text(rule, "description");
    if (
      title !== text(metadata, "title") ||
      description !== text(metadata, "description")
    )
      fail(
        `“${title}”: XCCDF and OVAL descriptions must match for this editor.`,
      );
    const criteria = one(def, "criteria");
    shape(criteria, ["criterion"], ["operator"]);
    value(criteria, "operator", "AND", true);
    const criterion = one(criteria, "criterion");
    leaf(criterion, ["test_ref", "comment"]);
    const testId = criterion.getAttribute("test_ref") || "";
    const test = tests.get(testId);
    if (!test || seenTests.has(testId))
      fail("Missing or shared OVAL test reference is unsupported.");
    seenTests.add(testId);
    shape(
      test,
      ["object", "state"],
      ["id", "version", "check", "check_existence", "comment"],
    );
    value(test, "version", "1");
    value(test, "check", "all");
    value(test, "check_existence", "at_least_one_exists");
    const testNamespace = test.namespaceURI || "";
    const objectRef = one(test, "object", testNamespace);
    leaf(objectRef, ["object_ref"]);
    const objectId = objectRef.getAttribute("object_ref") || "";
    const object = objects.get(objectId);
    if (!object || seenObjects.has(objectId))
      fail("Missing or shared OVAL object reference is unsupported.");
    seenObjects.add(objectId);
    value(object, "version", "1");
    const severity = rule.getAttribute("severity");
    if (severity !== "low" && severity !== "medium" && severity !== "high")
      fail(`“${title}”: unsupported severity.`);
    const result: Rule = {
      ...blankRule(id),
      id,
      title,
      description,
      severity,
      selected: selected.get(rule.getAttribute("id") || "") ?? true,
    };
    const stateRefs = children(test, "state", testNamespace);
    const takeState = (): Element => {
      if (stateRefs.length !== 1)
        fail(`${test.localName} requires exactly one state reference.`);
      const stateRef = stateRefs[0];
      leaf(stateRef, ["state_ref"]);
      const stateId = stateRef.getAttribute("state_ref") || "";
      const state = states.get(stateId);
      if (!state || seenStates.has(stateId))
        fail("Missing or shared OVAL state reference is unsupported.");
      seenStates.add(stateId);
      value(state, "version", "1");
      return state;
    };
    if (test.localName === "textfilecontent54_test" && testNamespace === I) {
      if (stateRefs.length) fail("Text-file checks cannot have a state.");
      shape(
        object,
        ["behaviors", "filepath", "pattern", "instance"],
        ["id", "version"],
      );
      const behaviors = one(object, "behaviors", I);
      leaf(behaviors, ["multiline"]);
      value(behaviors, "multiline", "true");
      const path = one(object, "filepath", I);
      leaf(path, ["operation", "datatype"]);
      const pattern = one(object, "pattern", I);
      leaf(pattern, ["operation", "datatype"]);
      value(pattern, "operation", "pattern match");
      const instance = one(object, "instance", I);
      leaf(instance, ["datatype", "operation"]);
      value(instance, "datatype", "int");
      value(instance, "operation", "greater than or equal");
      if (instance.textContent?.trim() !== "1")
        fail("Only checks for at least one matching instance are supported.");
      const pathValue = path.textContent || "";
      const patternValue = pattern.textContent || "";
      const prefix = "^[\\t ]*",
        suffix = "[\\t ]*$";
      if (
        pathValue.startsWith("/proc/sys/") &&
        patternValue.startsWith(prefix) &&
        patternValue.endsWith(suffix)
      ) {
        result.kind = "sysctl";
        result.sysctlName = pathValue.slice(10).replaceAll("/", ".");
        result.expectedValue = unescapeRegexLiteral(
          patternValue.slice(prefix.length, -suffix.length),
        );
      } else {
        result.kind = "textfile";
        result.path = pathValue;
        result.pattern = patternValue;
      }
    } else if (
      test.localName === "systemdunitproperty_test" &&
      testNamespace === L
    ) {
      shape(object, ["unit", "property"], ["id", "version"]);
      const state = takeState();
      shape(state, ["value"], ["id", "version"]);
      const expected = one(state, "value", L);
      leaf(expected, ["operation", "datatype"]);
      value(expected, "operation", "equals");
      result.kind = "systemd";
      result.unit = text(object, "unit");
      result.property = text(object, "property");
      result.expectedValue = expected.textContent || "";
    } else if (
      (test.localName === "dpkginfo_test" ||
        test.localName === "rpminfo_test") &&
      testNamespace === L
    ) {
      if (stateRefs.length) fail("Package checks cannot have a state.");
      shape(object, ["name"], ["id", "version"]);
      result.kind = test.localName === "dpkginfo_test" ? "dpkg" : "rpm";
      result.packageName = text(object, "name");
    } else if (test.localName === "file_test" && testNamespace === U) {
      shape(object, ["filepath"], ["id", "version"]);
      const state = takeState();
      const permissionNames = [
        "suid",
        "sgid",
        "sticky",
        "uread",
        "uwrite",
        "uexec",
        "gread",
        "gwrite",
        "gexec",
        "oread",
        "owrite",
        "oexec",
      ];
      shape(
        state,
        ["group_id", "user_id", ...permissionNames],
        ["id", "version"],
      );
      const numeric = (name: string) => {
        const node = one(state, name, U);
        leaf(node, ["datatype", "operation"]);
        return node.textContent || "";
      };
      const bit = (name: string, amount: number) => {
        const node = one(state, name, U);
        leaf(node, ["datatype", "operation"]);
        return node.textContent?.trim() === "true" ? amount : 0;
      };
      const special = bit("suid", 4) + bit("sgid", 2) + bit("sticky", 1);
      const user = bit("uread", 4) + bit("uwrite", 2) + bit("uexec", 1);
      const group = bit("gread", 4) + bit("gwrite", 2) + bit("gexec", 1);
      const other = bit("oread", 4) + bit("owrite", 2) + bit("oexec", 1);
      result.kind = "file";
      result.path = text(object, "filepath");
      result.groupId = numeric("group_id");
      result.ownerId = numeric("user_id");
      result.fileMode = `${special}${user}${group}${other}`;
    } else {
      fail(`Unsupported OVAL test type: ${test.localName}.`);
    }
    return result;
  });
  if (
    seenTests.size !== tests.size ||
    seenObjects.size !== objects.size ||
    seenStates.size !== states.size
  )
    fail(
      "ZIP contains unused tests or objects that this editor cannot preserve.",
    );
  const project: Project = {
    namespace,
    title: text(benchmark, "title"),
    profileTitle,
    description: text(benchmark, "description"),
    version: text(benchmark, "version"),
    status: statusValue as XccdfStatus,
    rules,
  };
  const errors = issues(project);
  if (errors.length) fail(errors.join("\n"));
  return project;
}
